version: '3.8'
services:
  web1:
    build: ./src
    volumes:
      - ./src:/src
      - shared-db:/src/data
    environment:
      SERVER_ID: SERVER-1

  web2:
    build: ./src
    volumes:
      - ./src:/src
      - shared-db:/src/data
    environment:
      SERVER_ID: SERVER-2
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
      - redis
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: ./src
    command: celery -A main.celery_worker worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./src:/src

volumes:
  shared-db:
    driver: local